apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: configuration-scratch
  annotations:
    meta.crossplane.io/maintainer: The Getting Started Organization <support@starter.org>
    meta.crossplane.io/source: github.com/upbound/configuration-scratch
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      This starter configuration is completely empty.
    meta.crossplane.io/readme: |
      This starter configuration is completely empty, allowing you to start
      entirely from scratch.
spec:
  crossplane:
    version: ">=v1.7.0-0"
  dependsOn:
  - provider: index.docker.io/erhancag/provider-aws-ec2
    version: v1.2.0-refactor-1fabbe60e57d4c9040a15ac6f1b080a24d803c50
