apiVersion: ulucinar.github.com/v1alpha1
kind: NopResource
metadata:
  name: nop
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  parameters:
    connSecret:
      name: conn-secret
      namespace: default