apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-nop
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  package: xpkg.upbound.io/crossplane-contrib/provider-nop:v0.3.0
  runtimeConfigRef:
    name: config-nop

---

apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: config-nop
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          containers:
            - name: package-runtime
              args:
                - -d
