apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xnopresources.ulucinar.github.com
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  compositeTypeRef:
    apiVersion: ulucinar.github.com/v1alpha1
    kind: XNopResource
  resources:
    - name: nopresource
      base:
        apiVersion: nop.crossplane.io/v1alpha1
        kind: NopResource
        spec:
          forProvider:
            conditionAfter:
              - conditionType: Ready
                conditionStatus: "True"
                time: 0s
              - conditionType: Synced
                conditionStatus: "True"
                time: 0s
          writeConnectionSecretToRef:
            name: name
            namespace: namespace
      patches:
        - fromFieldPath: spec.parameters.connSecret.name
          toFieldPath: spec.writeConnectionSecretToRef.name
          policy:
            fromFieldPath: Required
        - fromFieldPath: spec.parameters.connSecret.namespace
          toFieldPath: spec.writeConnectionSecretToRef.namespace
          policy:
            fromFieldPath: Required