apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xbuckets.ulucinar.github.com
spec:
  compositeTypeRef:
    apiVersion: ulucinar.github.com/v1alpha1
    kind: XBucket
  mode: Pipeline
  pipeline:
  - step: patch-and-transform
    functionRef:
      name: crossplane-contrib-function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      resources:
      - name: bucket
        base:
          apiVersion: storage.gcp.upbound.io/v1beta2
          kind: Bucket
          spec:
            forProvider:
              cors:
              - maxAgeSeconds: 3600
                method:
                - GET
                - HEAD
                - PUT
                - POST
                - DELETE
                origin:
                - http://image-store.com
                responseHeader:
                - '*'
              forceDestroy: true
              uniformBucketLevelAccess: true
              website:
                mainPageSuffix: index.html
                notFoundPage: 404.html

        patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.location
          toFieldPath: spec.forProvider.location
          policy:
            fromFieldPath: Required

