apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xvpcs.ulucinar.github.com
spec:
  group: ulucinar.github.com
  names:
    kind: XVPC
    plural: xvpcs
  claimNames:
    kind: VPC
    plural: vpcs
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                description: VPC parameters.
                properties:
                  region:
                    type: string
                    description: Region of the VPC.
                required:
                - region
            required:
            - parameters
