apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xbuckets.ulucinar.github.com
spec:
  group: ulucinar.github.com
  names:
    kind: XBucket
    plural: xbuckets
  claimNames:
    kind: Bucket
    plural: buckets
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                description: Bucket parameters.
                properties:
                  location:
                    type: string
                    description: Location of the storage bucket.
                required:
                - location
            required:
            - parameters
